list_items:
  seneyed-vpu-0101:
    apt:
      - nmap
      - wget
      - curl
  sengame-vpu-0101:
    apt:
      - nmap
      - nmap
      - curl
  local-host-system:
    apt:
      - nmap
      - nmap
      - curl

