list_items:
  seneyed-vpu-0101:
    apt:
      - nmap
      - wget
      - curl
  sengame-vpu-0101:
    apt:
      - nmap
      - wget
      - curl
  local-host-system-home:
    apt:
      - nmap
      - wget
      - curl
  local-host-docker:
    apt:
      - nmapgg
      - wget
      - curl

