- name: file update
  hosts: all #sengame-vpu-0101, sengame-vpu-0101
  tasks:
    - name: copy file from main to remote hosts
      copy:
        #content: "demo line 1 from content\n"
        remote_src: yes
        src: /root/dfile
        dest: /home/sensen/dfile
      when:
        - inventory_hostname == "sengame-vpu-0101" or inventory_hostname = "sengame-vpu-0101"
      delegate_to: local-host
      register: result
      
    - name: Print where the file is copied
      debug:
        msg: "The absolute path of the file is {{result.dest}}."
