- name: file update
  hosts: all
  tasks:
    - name: copy file from main to remote hosts
      copy:
        #content: demo line 1 from content
        src: /home/sensen/demo_file
        dest: /home/sensen/demo_file
      #debug:
       # msg: "file copied"
