- name: file update
  hosts: all #sengame-vpu-0101, sengame-vpu-0101
  tasks:
    - name: copy file from main to remote hosts
      copy:
        #content: "demo line 1 from content\n"
        remote_src: yes
        src: /home/sensen/dfile
        dest: /home/sensen/dfile
      when: ansible_hostname in [ "sengame-vpu-0101" , "seneyed-vpu-0101"]
      delegate_to: local-host-system
      register: result
      
    - name: Print where the file is copied
      debug:
        msg: "The absolute path of the file is {{result.dest}}."
      when: ansible_hostname in [ "sengame-vpu-0101" , "seneyed-vpu-0101"]
      
      

    - name: Print the text file to stdout
      command: "cat /tmp/file.txt"
      register: result
      when: ansible_hostname in [  "seneyed-vpu-0101"]
      
    - name: Print 
      debug:
        msg: "{{result.stdout}}."
      when: ansible_hostname in [  "seneyed-vpu-0101"]
      
      
    - name: Print the text file to stdout
      command: "cat /tmp/file.txt"
      register: result
      when: ansible_hostname in [ "sengame-vpu-0101" ]
      
    - name: Print 
      debug:
        msg: "{{result.stdout}}."
      when: ansible_hostname in [ "sengame-vpu-0101" ]
