- name: file check
  hosts: local-host
  tasks:
    - name: Ensure the file is present
      stat:
        path: /root/dfile
      register: file_check
    #  debug:
     #   msg: "The file {{ file_check.stat.exists }}"
