- name: file update
  hosts: sengame-vpu-0101, sengame-vpu-0101
  tasks:
    - name: copy file from main to remote hosts
      copy:
        #content: "demo line 1 from content\n"
        remote_src: yes
        src: /root/dfile
        dest: /home/sensen/demo_file
      delegate_to: local-host
      #debug:
       # msg: "file copied"
