- name: file update
  hosts: all
  tasks:
    - name: copy file from main to remote hosts
      copy:
        src: demo_file
        dest: /home/sensen/demo_file
      debug:
        msg: "Hello World!"
