- name: file check
  hosts: seneyed-vpu-0101
  tasks:
    - name: Ensure the file is present
      stat:
        path: ./dfile
      register: file_check
    - name: Tell whether the file exists
      debug:
        msg: "The file exists : {{ file_check.stat.exists }}"
