

- name: set fact
  hosts:  all
  vars_files: 
    - configuration.yml

  tasks:
  
    - name: Take snapshot first
      command: sudo sh take_snashop.sh
        
    - name: Ansible Dictionaries Usage Example
      apt:
        name: "{{item}}"
        update_cache: yes
        register: a
      register: result
      with_items: "{{ list_items[inventory_hostname]['apt']}}"
      #until: result.results.
    
    - name: check for failure and restore
      command: sudo sh restore.sh
      with_items: "{{result.results}}"
      when: item.failed == True
