

- name: set fact
  hosts:  all
  vars_files: 
    - configuration.yml

  tasks:
  
  ### Take a snap shot first
  
    - name: Ansible Dictionaries Usage Example
      apt:
        name: "{{item}}"
        update_cache: yes
      register: result
      with_items: "{{ list_items[inventory_hostname]['apt']}}"
      #until: result.results.
    
    - name: check for failure and restore
      #command: 
      debug: 
       # var: "{{item}}"
        msg: "Is the result for {{item.item}} failure? : {{item.failed}} "
      with_items: "{{result.results}}"
      when: item.failed
