#- import_playbook: configuration.yml

#- name: Including vars
 # include_vars: 
  #   file: configuration.yml
   #  name: list_items

- name: set fact
  hosts:  all
  vars_files: 
    - configuration.yml


#- name: printingg
 # hosts: all
  #- tasks: including vars
   # include_vars: configuration.yml
  tasks:
    - name: Ansible Dictionaries Usage Example
      apt:
        name: "{{item}}"
        update_cache: yes
      register: result
      with_items: "{{ list_items[inventory_hostname]['apt']}}"
      #when: result.failed != "True"
    
    - name: check for failure and restore
      #command: 
      debug: 
        msg: "Is the result for {{item}} failure? : {{item.failed}} "
      with_items: "{{result.results}}"
