

- name: set fact
  hosts:  all
  vars_files: 
    - configuration.yml

  tasks:
  
 #   - name: Take snapshot first
  #    command: sudo sh take_snashop.sh
        
    - name: Attempt to install apt packages
      apt:
        name: "{{item}}"
        update_cache: yes
      register: result
      with_items: "{{ list_items[inventory_hostname]['apt']}}"
      #failed_when: one of them is failure
      #ignore_errors: true
      
      #until: result.results.
       #### Should I ignore error?
    
    - name: Check for failure and restore
      command: sudo sh restore.sh
      with_items: "{{result.results}}"
      when: item.failed == True
      ignore_unreachable: true

