


- name: Launch configuration for seneyed-vpu-0101
  hosts:  seneyed-vpu-0101
  tasks:
   - name: Launch syncing for seneyed-vpu-0101
     command: sudo timeshift --create --comments "A new backup"
     delegate_to: local-host-system   

     
  
  
- name: Launch configuration for sengame-vpu-0101
  hosts:  sengame-vpu-0101
  tasks:
   - name: Launch syncing for sengame-vpu-0101 
     command: sudo timeshift --create --comments "A new backup"
     delegate_to: local-host-system   
     
     
     
  
