


- name: Launch configuration for local-host-docker
  hosts:  local-host-docker
  tasks:
   - name: Print inventory hostname
     debug:
       msg: "{{inventory_hostname}}"
   - name: Launch syncing for local-host-docker
     command: curl -X POST -k http://192.168.49.2:30080/api/v2/job_templates/10/launch/ \
              --user "sengame_user:testsensen" -H "Content-Type:application/json" \
              -d '{"limit":"{{inventory_hostname}}"}'
     delegate_to: local-host-system-home  

     
  
  
- name: Launch configuration for local-host-system-home
  hosts:  local-host-system-home
  tasks:
   - name: Launch syncing for local-host-system-home
     command: curl -X POST -k http://192.168.49.2:30080/api/v2/job_templates/10/launch/ \
              --user "sengame_user:testsensen" -H "Content-Type:application/json" \
              -d '{"limit":"{{inventory_hostname}}"}'
     delegate_to: local-host-system-home   
     
     
     
  


