


- name: Launch configuration for seneyed-vpu-0101
  hosts:  seneyed-vpu-0101
  tasks:
   - name: Launch syncing for seneyed-vpu-0101
     command: curl -X POST -k http://192.168.49.2:30080/api/v2/job_templates/9/launch/ \
            --user "sengame_user:testsensen" -H "Content-Type: application/json" \
            -d '{ "limit":"{{inventory_hostname}}"}'
     delegate_to: local-host-system   

     
  
  
- name: Launch configuration for sengame-vpu-0101
  hosts:  sengame-vpu-0101
  tasks:
   - name: Launch syncing for sengame-vpu-0101 
     command: curl -X POST -k http://192.168.49.2:30080/api/v2/job_templates/9/launch/ \
            --user "sengame_user:testsensen" -H "Content-Type: application/json" \
            -d '{ "limit":"{{inventory_hostname}}"}'
     delegate_to: local-host-system   
     
     
     
  


