- name: import playbook with configuration
  include_vars: configuration.yml
    
#- name: include variables
 # hosts: local-host-system
  #tasks:
   # - name: include variables
    #  include_vars: /home/sensen/configuration.yaml
     # delegate_to: local-host-system
    
    #file: configuration.yml 
    
- name: configuration print
  hosts: sengame-vpu-0101 ,seneyed-vpu-0101 #local-host-system
  become: true    
  tasks:
    - name: print
      debug:
        msg: "{{ list_items }}"
