- import_playbook: configuration.yml

#- name: Including vars
 # include_vars: 
  #   file: configuration.yml
   #  name: list_items
  
- name: print
  hosts: all
  tasks:
    - name: Ansible Dictionaries Usage Example
      debug:
        msg: " A list of student details: {{ list_items }}"
