#- include_vars:
    #file: configuration.yml
    
- name: include variables
  hosts: local-host-system
  tasks:
    - include_vars: /home/sensen/configuration.yaml
    
    #file: configuration.yml 
    
- name: configuration print
  hosts: sengame-vpu-0101 ,seneyed-vpu-0101 #local-host-system
  become: true    
  tasks:
  - name: print
    debug:
      msg: "{{ list_items }}"
