- name: set fact
  hosts:  all
  vars_files: 
    - configuration.yml

  tasks:
    - name: Sequence 1
      debug:
        msg: "{{item}}"
      register: result
      with_sequence: start=0 end=5
      failed_when: item == 3
